component:
  name: landing_zone_organization
  template:
    resource:
      aws_organizations_organization:
        landing_zone_organization:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          aws_service_access_principals: var.landing_zone_organization_service_access_principals
          enabled_policy_types: var.landing_zone_organization_enabled_policy_types
          feature_set: var.landing_zone_organization_feature_set
    output:
      id:
        value: aws_organizations_organization.landing_zone_organization.id
      thub_id:
        value: aws_organizations_organization.landing_zone_organization.id
      accounts:
        value: aws_organizations_organization.landing_zone_organization.accounts
      roots:
        value: aws_organizations_organization.landing_zone_organization.roots
      landing_zone_organization_id:
        value: aws_organizations_organization.landing_zone_organization.id
      landing_zone_organization_accounts:
        value: aws_organizations_organization.landing_zone_organization.accounts
      landing_zone_organization_roots:
        value: aws_organizations_organization.landing_zone_organization.roots
