component:
  name: landing_zone_organization_policy_attachment
  dependsOn:
    - landing_zone_organization_unit
    - landing_zone_organization_policy
  template:
    data:
      aws_organizations_organization:
        landing_zone_organization: {}
    dynamic:
      data:
        terraform_remote_state:
          - component: landing_zone_organization_policy
            name: landing_zone_organization_policy
    locals:
      organization_policy_thub_id: >-
        data.terraform_remote_state.landing_zone_organization_policy.outputs.thub_id["default"]
    resource:
      aws_organizations_policy_attachment:
        landing_zone_organization_policy_attachment:
          count: >-
            length(data.aws_organizations_organization.landing_zone_organization.accounts[*].id)
          policy_id: local.organization_policy_thub_id
          target_id: >-
            element(data.aws_organizations_organization.landing_zone_organization.accounts[*].id,
            count.index)
    output:
      id:
        value: >-
          aws_organizations_policy_attachment.landing_zone_organization_policy_attachment.id
      thub_id:
        value: >-
          aws_organizations_policy_attachment.landing_zone_organization_policy_attachment.id
