component:
  name: landing_zone_security_group
  dependsOn:
    - landing_zone_vpc
  template:
    locals:
      elements_landing_zone_vpc_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"]
      elements_landing_zone_security_group_tags_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_security_group_tags"]
      elements_landing_zone_security_group_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_security_group_resource"]
    data:
      aws_vpc:
        vpc_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"])
          cidr_block: >-
            local.elements_landing_zone_vpc_data_map["config_${count.index}"]["cidr_block"]
    resource:
      aws_security_group:
        landing_zone_security_group:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_security_group_resource"])
          name: >-
            local.elements_landing_zone_security_group_map["config_${count.index}"]["name"]
          description: >-
            local.elements_landing_zone_security_group_map["config_${count.index}"]["description"]
          vpc_id: 'element(data.aws_vpc.vpc_selected.*.id, count.index)'
          tags: >-
            merge(local.elements_landing_zone_security_group_tags_map["config_${count.index}"],
            map("LzHash", sha1("${tfvar.terrahub["project"]["code"]}
            ${tfvar.terrahub["component"]["name"]}
            ${tfvar.terrahub["landing_zone_providers"]["0"]} ${count.index}")))
    output:
      ids:
        value: aws_security_group.landing_zone_security_group.*.id
      thub_ids:
        value: aws_security_group.landing_zone_security_group.*.id
      landing_zone_security_group_ids:
        value: >-
          { for sg in aws_security_group.landing_zone_security_group.*:
          lookup(sg.tags, "LzHash", sg.id) => sg.id }
