component:
  name: landing_zone_route_igw
  dependsOn:
    - landing_zone_route_table
    - landing_zone_gateway_igw
  template:
    locals:
      elements_landing_zone_vpc_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"]
      elements_landing_zone_route_table_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_table_data"]
      elements_landing_zone_route_igw_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_igw_resource"]
    data:
      aws_vpc:
        vpc_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"])
          cidr_block: >-
            local.elements_landing_zone_vpc_data_map["config_${count.index}"]["cidr_block"]
      aws_route_table:
        route_table_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_table_data"])
          vpc_id: 'element(data.aws_vpc.vpc_selected.*.id, count.index)'
          filter!:
            name: 'tag:LzHash'
            values:
              - >-
                local.elements_landing_zone_route_table_data_map["config_${count.index}"]["LzHash"]
      aws_internet_gateway:
        internet_gateway_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"])
          filter!:
            - name: attachment.vpc-id
              values:
                - 'element(data.aws_vpc.vpc_selected.*.id, count.index)'
    resource:
      aws_route:
        landing_zone_route_igw:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_igw_resource"])
          route_table_id: 'element(data.aws_route_table.route_table_selected.*.id, count.index)'
          destination_cidr_block: >-
            local.elements_landing_zone_route_igw_map["config_${count.index}"]["destination_cidr_block"]
          gateway_id: >-
            element(distinct(data.aws_internet_gateway.internet_gateway_selected.*.id),
            count.index)
    output:
      ids:
        value: aws_route.landing_zone_route_igw.*.id
      thub_ids:
        value: aws_route.landing_zone_route_igw.*.id
      landing_zone_route_igw_ids:
        value: >-
          { for route_igw in aws_route.landing_zone_route_igw.*: route_igw.id =>
          route_igw.id }
