component:
  name: landing_zone_route_table_tgw
  dependsOn:
    - landing_zone_gateway_tgw
  template:
    locals:
      elements_landing_zone_gateway_tgw_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_gateway_tgw_data"]
      elements_landing_zone_route_table_tgw_tags_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_table_tgw_tags"]
    data:
      aws_ec2_transit_gateway:
        gateway_tgw_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_gateway_tgw_data"])
          filter!:
            - name: options.amazon-side-asn
              values:
                - >-
                  local.elements_landing_zone_gateway_tgw_data_map["config_${count.index}"]["amazon_side_asn"]
    resource:
      aws_route_table:
        landing_zone_route_table_tgw:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_table_tgw_tags"])
          transit_gateway_id: >-
            element(data.aws_ec2_transit_gateway.gateway_tgw_selected.*.id,
            count.index)
          tags: >-
            merge(local.elements_landing_zone_route_table_tgw_tags_map["config_${count.index}"],
            map("LzHash", sha1("${tfvar.terrahub["project"]["code"]}
            ${tfvar.terrahub["component"]["name"]}
            ${tfvar.terrahub["landing_zone_providers"]["0"]} ${count.index}")))
    output:
      ids:
        value: aws_route_table.landing_zone_route_table_tgw.*.id
      thub_ids:
        value: aws_route_table.landing_zone_route_table_tgw.*.id
      landing_zone_route_table_tgw_ids:
        value: >-
          { for route_table_tgw in
          aws_route_table.landing_zone_route_table_tgw.*:
          lookup(route_table_tgw.tags, "LzHash", route_table_tgw.id) =>
          route_table_tgw.id }
