component:
  name: landing_zone_code_pipeline_role
  template:
    resource:
      aws_iam_role:
        landing_zone_code_pipeline_role:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          assume_role_policy: 'file("${local.component["path"]}/iam_trust_policy.json.tpl")'
          description: var.landing_zone_code_pipeline_role_description
          force_detach_policies: var.landing_zone_code_pipeline_role_force_detach_policies
          name: var.landing_zone_code_pipeline_role_name
          path: var.landing_zone_code_pipeline_role_path
    output:
      id:
        value: aws_iam_role.landing_zone_code_pipeline_role.id
      thub_id:
        value: aws_iam_role.landing_zone_code_pipeline_role.id
      name:
        value: aws_iam_role.landing_zone_code_pipeline_role.name
      arn:
        value: aws_iam_role.landing_zone_code_pipeline_role.arn
      landing_zone_code_pipeline_role_id:
        value: aws_iam_role.landing_zone_code_pipeline_role.id
      landing_zone_code_pipeline_role_name:
        value: aws_iam_role.landing_zone_code_pipeline_role.name
      landing_zone_code_pipeline_role_arn:
        value: aws_iam_role.landing_zone_code_pipeline_role.arn
