component:
  name: landing_zone_route_cgw
  dependsOn:
    - landing_zone_route_table
    - landing_zone_gateway_vgw
  template:
    locals:
      elements_landing_zone_vpc_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"]
      elements_landing_zone_route_table_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_table_data"]
      elements_landing_zone_gateway_cgw_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_gateway_cgw_data"]
      elements_landing_zone_route_cgw_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_cgw_resource"]
    data:
      aws_vpc:
        vpc_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"])
          cidr_block: >-
            local.elements_landing_zone_vpc_data_map["config_${count.index}"]["cidr_block"]
      aws_route_table:
        route_table_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_table_data"])
          vpc_id: 'element(data.aws_vpc.vpc_selected.*.id, count.index)'
          filter!:
            name: 'tag:Name'
            values:
              - >-
                local.elements_landing_zone_route_table_data_map["config_${count.index}"]["name"]
      aws_customer_gateway:
        aws_customer_gateway:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_gateway_cgw_data"])
          filter!:
            - name: 'tag:LzHash'
              values:
                - >-
                  local.elements_landing_zone_gateway_cgw_data_map["config_${count.index}"]["LzHash"]
    resource:
      aws_route:
        landing_zone_route_cgw:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_cgw_resource"])
          route_table_id: 'element(data.aws_route_table.route_table_selected.*.id, count.index)'
          destination_cidr_block: >-
            local.elements_landing_zone_route_cgw_map["config_${count.index}"]["destination_cidr_block"]
          gateway_id: >-
            element(distinct(data.aws_customer_gateway.aws_customer_gateway.*.id),
            count.index)
    output:
      ids:
        value: aws_route.landing_zone_route_cgw.*.id
      thub_ids:
        value: aws_route.landing_zone_route_cgw.*.id
      landing_zone_route_cgw_ids:
        value: >-
          { for route_cgw in aws_route.landing_zone_route_cgw.*: route_cgw.id =>
          route_cgw.id }
