component:
  name: landing_zone_cloudtrail_s3_bucket_policy
  dependsOn:
    - landing_zone_cloudtrail_s3_bucket
  template:
    dynamic:
      data:
        terraform_remote_state:
          - component: landing_zone_cloudtrail_s3_bucket
            name: landing_zone_cloudtrail_s3_bucket
    locals:
      s3_bucket_policy_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["s3_bucket_policy_resource"]
      remote_state_s3_bucket: >-
        data.terraform_remote_state.landing_zone_cloudtrail_s3_bucket.outputs["landing_zone_cloudtrail_s3_bucket_id"]
    data:
      template_file:
        landing_zone_cloudtrail_s3_bucket_policy:
          provider!: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: length(local.s3_bucket_policy_map)
          template: >-
            file("${local.component["path"]}/policies/${local.s3_bucket_policy_map["config_${count.index}"]["policy_file_name"]}.json.tpl")
          vars:
            s3_bucket_name: >-
              local.remote_state_s3_bucket["${tfvar.terrahub["landing_zone_providers"]["0"]}"][local.s3_bucket_policy_map["config_${count.index}"]["bucket_name"]]
            account_id: 'var.${tfvar.terrahub["landing_zone_providers"]["0"]}_account_id'
    resource:
      aws_s3_bucket_policy:
        landing_zone_cloudtrail_s3_bucket_policy:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: length(local.s3_bucket_policy_map)
          bucket: >-
            local.remote_state_s3_bucket["${tfvar.terrahub["landing_zone_providers"]["0"]}"][local.s3_bucket_policy_map["config_${count.index}"]["bucket_name"]]
          policy: >-
            element(data.template_file.landing_zone_cloudtrail_s3_bucket_policy.*.rendered,
            count.index)
