component:
  name: landing_zone_route_table
  dependsOn:
    - landing_zone_vpc
  template:
    locals:
      elements_landing_zone_vpc_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"]
      elements_landing_zone_route_table_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_table_resource"]
      elements_landing_zone_route_table_tags_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_table_tags"]
    data:
      aws_vpc:
        vpc_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"])
          cidr_block: >-
            local.elements_landing_zone_vpc_data_map["config_${count.index}"]["cidr_block"]
    resource:
      aws_route_table:
        landing_zone_route_table:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_table_resource"])
          vpc_id: 'element(data.aws_vpc.vpc_selected.*.id, count.index)'
          tags: >-
            merge(local.elements_landing_zone_route_table_tags_map["config_${count.index}"],
            map("LzHash", sha1("${tfvar.terrahub["project"]["code"]}
            ${tfvar.terrahub["component"]["name"]}
            ${tfvar.terrahub["landing_zone_providers"]["0"]} ${count.index}")))
    output:
      ids:
        value: aws_route_table.landing_zone_route_table.*.id
      thub_ids:
        value: aws_route_table.landing_zone_route_table.*.id
      landing_zone_route_table_ids:
        value: >-
          { for route_table in aws_route_table.landing_zone_route_table.*:
          lookup(route_table.tags, "LzHash", route_table.id) => route_table.id }
