component:
  name: landing_zone_secretsmanager_secret
  template:
    locals:
      elements_landing_zone_secretsmanager_secret_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["secretsmanager_secret_resource"]
      elements_landing_zone_secretsmanager_secret_tags_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["secretsmanager_secret_tags"]
    resource:
      aws_secretsmanager_secret:
        landing_zone_secretsmanager_secret:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["secretsmanager_secret_resource"])
          name: >-
            local.elements_landing_zone_secretsmanager_secret_map["config_${count.index}"]["name"]
          description: >-
            local.elements_landing_zone_secretsmanager_secret_map["config_${count.index}"]["description"]
          recovery_window_in_days: >-
            local.elements_landing_zone_secretsmanager_secret_map["config_${count.index}"]["recovery_window_in_days"]
          tags: >-
            merge(local.elements_landing_zone_secretsmanager_secret_tags_map["config_${count.index}"],
            map("LzHash", sha1("${tfvar.terrahub["project"]["code"]}
            ${tfvar.terrahub["component"]["name"]}
            ${tfvar.terrahub["landing_zone_providers"]["0"]}
            ${local.elements_landing_zone_secretsmanager_secret_map["config_${count.index}"]["name"]}")))
    output:
      ids:
        value: aws_secretsmanager_secret.landing_zone_secretsmanager_secret.*.id
      arns:
        value: aws_secretsmanager_secret.landing_zone_secretsmanager_secret.*.arn
      landing_zone_secretsmanager_secret_ids:
        value: >-
          { for secretsmanager_secret in
          aws_secretsmanager_secret.landing_zone_secretsmanager_secret.*:
          secretsmanager_secret.name => secretsmanager_secret.id }
      landing_zone_secretsmanager_secret_arns:
        value: >-
          { for secretsmanager_secret in
          aws_secretsmanager_secret.landing_zone_secretsmanager_secret.*:
          secretsmanager_secret.name => secretsmanager_secret.arn }
