component:
  name: landing_zone_network_acl
  dependsOn:
    - landing_zone_vpc
    - landing_zone_subnet
  template:
    locals:
      elements_landing_zone_vpc_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"]
      elements_landing_zone_subnet_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_subnet_data"]
      elements_landing_zone_network_acl_tags_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_network_acl_tags"]
      elements_landing_zone_network_acl_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_network_acl_resource"]
    data:
      aws_vpc:
        vpc_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"])
          cidr_block: >-
            local.elements_landing_zone_vpc_data_map["config_${count.index}"]["cidr_block"]
      aws_subnet:
        subnet_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_subnet_data"])
          vpc_id: >-
            element(data.aws_vpc.vpc_selected.*.id,
            local.elements_landing_zone_subnet_data_map["config_${count.index}"]["vpc_index"])
          cidr_block: >-
            local.elements_landing_zone_subnet_data_map["config_${count.index}"]["cidr_block"]
    resource:
      aws_network_acl:
        landing_zone_network_acl:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_network_acl_resource"])
          vpc_id: 'element(data.aws_vpc.vpc_selected.*.id, count.index)'
          tags: >-
            merge(local.elements_landing_zone_network_acl_tags_map["config_${count.index}"],
            map("LzHash", sha1("${tfvar.terrahub["project"]["code"]}
            ${tfvar.terrahub["component"]["name"]}
            ${tfvar.terrahub["landing_zone_providers"]["0"]} ${count.index}")))
          subnet_ids: >-
            slice(data.aws_subnet.subnet_selected.*.id,
            local.elements_landing_zone_network_acl_map["config_${count.index}"]["subnets_from_index"],
            local.elements_landing_zone_network_acl_map["config_${count.index}"]["subnets_to_index"])
    output:
      ids:
        value: aws_network_acl.landing_zone_network_acl.*.id
      thub_ids:
        value: aws_network_acl.landing_zone_network_acl.*.id
      landing_zone_network_acl_ids:
        value: >-
          { for network_acl in aws_network_acl.landing_zone_network_acl.*:
          lookup(network_acl.tags, "LzHash", network_acl.id) => network_acl.id }
