component:
  name: landing_zone_ssm_parameter
  template:
    locals:
      elements_landing_zone_ssm_parameter_tags_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_ssm_parameter_tags"]
      elements_landing_zone_ssm_parameter_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_ssm_parameter_resource"]
    resource:
      aws_ssm_parameter:
        landing_zone_ssm_parameter:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_ssm_parameter_resource"])
          name: >-
            local.elements_landing_zone_ssm_parameter_map["config_${count.index}"]["name"]
          type: >-
            local.elements_landing_zone_ssm_parameter_map["config_${count.index}"]["type"]
          value: >-
            local.elements_landing_zone_ssm_parameter_map["config_${count.index}"]["value"]
          description: >-
            local.elements_landing_zone_ssm_parameter_map["config_${count.index}"]["description"]
          tier: >-
            local.elements_landing_zone_ssm_parameter_map["config_${count.index}"]["tier"]
          key_id: >-
            local.elements_landing_zone_ssm_parameter_map["config_${count.index}"]["key_id"]
          overwrite: >-
            local.elements_landing_zone_ssm_parameter_map["config_${count.index}"]["overwrite"]
          allowed_pattern: >-
            local.elements_landing_zone_ssm_parameter_map["config_${count.index}"]["allowed_pattern"]
          tags: >-
            merge(local.elements_landing_zone_ssm_parameter_tags_map["config_${count.index}"],
            map("LzHash", sha1("${tfvar.terrahub["project"]["code"]}
            ${tfvar.terrahub["component"]["name"]}
            ${tfvar.terrahub["landing_zone_providers"]["0"]}
            ${local.elements_landing_zone_ssm_parameter_map["config_${count.index}"]["name"]}")))
    output:
      arns:
        value: aws_ssm_parameter.landing_zone_ssm_parameter.*.arn
      names:
        value: aws_ssm_parameter.landing_zone_ssm_parameter.*.name
      descriptions:
        value: aws_ssm_parameter.landing_zone_ssm_parameter.*.description
      types:
        value: aws_ssm_parameter.landing_zone_ssm_parameter.*.type
      values:
        value: aws_ssm_parameter.landing_zone_ssm_parameter.*.value
      versions:
        value: aws_ssm_parameter.landing_zone_ssm_parameter.*.version
      landing_zone_ssm_parameter_arns:
        value: >-
          { for ssm_parameter in aws_ssm_parameter.landing_zone_ssm_parameter.*:
          ssm_parameter.name => ssm_parameter.id }
      landing_zone_ssm_parameter_names:
        value: >-
          { for ssm_parameter in aws_ssm_parameter.landing_zone_ssm_parameter.*:
          ssm_parameter.name => ssm_parameter.name }
