component:
  name: landing_zone_pipeline_artifact_s3_bucket
  template:
    resource:
      aws_s3_bucket:
        landing_zone_pipeline_artifact_s3_bucket:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          bucket: var.landing_zone_pipeline_artifact_s3_bucket_name
          versioning!:
            enabled: var.landing_zone_pipeline_artifact_s3_bucket_versioning
          server_side_encryption_configuration!:
            rule!:
              apply_server_side_encryption_by_default!:
                sse_algorithm: var.landing_zone_pipeline_artifact_s3_bucket_sse_algorithm
    output:
      id:
        value: aws_s3_bucket.landing_zone_pipeline_artifact_s3_bucket.id
      thub_id:
        value: aws_s3_bucket.landing_zone_pipeline_artifact_s3_bucket.id
      arn:
        value: aws_s3_bucket.landing_zone_pipeline_artifact_s3_bucket.arn
      bucket:
        value: aws_s3_bucket.landing_zone_pipeline_artifact_s3_bucket.bucket
      landing_zone_pipeline_artifact_s3_bucket_id:
        value: >-
          { for pipeline_artifact_s3_bucket in
          aws_s3_bucket.landing_zone_pipeline_artifact_s3_bucket.*:
          pipeline_artifact_s3_bucket.bucket => pipeline_artifact_s3_bucket.id }
      landing_zone_pipeline_artifact_s3_bucket_arn:
        value: >-
          { for pipeline_artifact_s3_bucket in
          aws_s3_bucket.landing_zone_pipeline_artifact_s3_bucket.*:
          pipeline_artifact_s3_bucket.bucket => pipeline_artifact_s3_bucket.arn
          }
      landing_zone_pipeline_artifact_s3_bucket_bucket:
        value: >-
          { for pipeline_artifact_s3_bucket in
          aws_s3_bucket.landing_zone_pipeline_artifact_s3_bucket.*:
          pipeline_artifact_s3_bucket.bucket =>
          pipeline_artifact_s3_bucket.bucket }
