component:
  name: landing_zone_organization_accounts_non_master
  dependsOn:
    - landing_zone_organization
  template:
    data:
      aws_organizations_organization:
        landing_zone_organization: {}
    locals:
      elements_landing_zone_organization_accounts_non_master_map: 'var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider'
    resource:
      aws_organizations_account:
        landing_zone_organization_accounts_non_master:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(local.elements_landing_zone_organization_accounts_non_master_map)
          name: >-
            local.elements_landing_zone_organization_accounts_non_master_map["config_${count.index}"]["name"]
          email: >-
            local.elements_landing_zone_organization_accounts_non_master_map["config_${count.index}"]["email"]
          parent_id: >-
            lookup(element(data.aws_organizations_organization.landing_zone_organization.non_master_accounts,
            local.elements_landing_zone_organization_accounts_non_master_map["config_${count.index}"]["organization_index"]),
            "id")
    output:
      ids:
        value: >-
          aws_organizations_account.landing_zone_organization_accounts_non_master.*.id
      thub_ids:
        value: >-
          aws_organizations_account.landing_zone_organization_accounts_non_master.*.id
      arns:
        value: >-
          aws_organizations_account.landing_zone_organization_accounts_non_master.*.arn
      landing_zone_organization_accounts_non_master_ids:
        value: >-
          { for organization_accounts_non_master in
          aws_organizations_account.landing_zone_organization_accounts_non_master.*:
          organization_accounts_non_master.name =>
          organization_accounts_non_master.id }
      landing_zone_organization_accounts_non_master_arns:
        value: >-
          { for organization_accounts_non_master in
          aws_organizations_account.landing_zone_organization_accounts_non_master.*:
          organization_accounts_non_master.name =>
          organization_accounts_non_master.arn }
