component:
  name: landing_zone_code_pipeline_role_policy
  dependsOn:
    - landing_zone_pipeline_s3_bucket
    - landing_zone_pipeline_artifact_s3_bucket
    - landing_zone_code_pipeline_role
    - landing_zone_code_build
  template:
    data:
      terraform_remote_state:
        landing_zone_pipeline_s3_bucket:
          backend: local
          config:
            path: >-
              ${tfvar.terrahub["tfstate_path"]}/landing_zone_pipeline_s3_bucket/terraform.tfstate
        landing_zone_pipeline_artifact_s3_bucket:
          backend: local
          config:
            path: >-
              ${tfvar.terrahub["tfstate_path"]}/landing_zone_pipeline_artifact_s3_bucket/terraform.tfstate
        landing_zone_code_pipeline_role:
          backend: local
          config:
            path: >-
              ${tfvar.terrahub["tfstate_path"]}/landing_zone_code_pipeline_role/terraform.tfstate
        landing_zone_code_build:
          backend: local
          config:
            path: >-
              ${tfvar.terrahub["tfstate_path"]}/landing_zone_code_build/terraform.tfstate
      template_file:
        landing_zone_code_pipeline_role_policy:
          template: 'file("${local.component["path"]}/iam_assume_policy.json.tpl")'
          vars:
            s3_bucket_arn: data.terraform_remote_state.landing_zone_pipeline_s3_bucket.arn
            artifact_s3_bucket_arn: >-
              data.terraform_remote_state.landing_zone_pipeline_artifact_s3_bucket.arn
            code_build_arn: data.terraform_remote_state.landing_zone_code_build.arn
    resource:
      aws_iam_role_policy:
        landing_zone_code_pipeline_role_policy:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          name: var.landing_zone_code_pipeline_role_policy_name
          policy: data.template_file.landing_zone_code_pipeline_role_policy.rendered
          role: data.terraform_remote_state.landing_zone_code_pipeline_role.id
    output:
      id:
        value: aws_iam_role_policy.landing_zone_code_pipeline_role_policy.id
      thub_id:
        value: aws_iam_role_policy.landing_zone_code_pipeline_role_policy.id
      name:
        value: aws_iam_role_policy.landing_zone_code_pipeline_role_policy.name
