component:
  name: landing_zone_config_organization_custom_rule
  template:
    locals:
      elements_landing_zone_config_organization_custom_rule_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_config_organization_custom_rule_resource"]
    resource:
      aws_config_organization_custom_rule:
        landing_zone_config_organization_custom_rule:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_config_organization_custom_rule_resource"])
          name: >-
            local.elements_landing_zone_config_organization_custom_rule_map["config_${count.index}"]["name"]
          lambda_function_arn: >-
            arn:aws:lambda:${var.${tfvar.terrahub["landing_zone_providers"]["0"]}_region}:${var.${tfvar.terrahub["landing_zone_providers"]["0"]}_account_id}:function:${local.elements_landing_zone_config_organization_custom_rule_map["config_${count.index}"]["lambda_function_name"]}
          trigger_types: >-
            split("|",
            local.elements_landing_zone_config_organization_custom_rule_map["config_${count.index}"]["trigger_types"])
    output:
      arns:
        value: >-
          aws_config_organization_custom_rule.landing_zone_config_organization_custom_rule.*.arn
      landing_zone_config_organization_custom_rule_arns:
        value: >-
          { for config_organization_custom_rule in
          aws_config_organization_custom_rule.landing_zone_config_organization_custom_rule.*:
          config_organization_custom_rule.name =>
          config_organization_custom_rule.arn }
