component:
  name: landing_zone_config_organization_managed_rule
  template:
    locals:
      elements_landing_zone_config_organization_managed_rule_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_config_organization_managed_rule_resource"]
    resource:
      aws_config_organization_managed_rule:
        landing_zone_config_organization_managed_rule:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_config_organization_managed_rule_resource"])
          name: >-
            local.elements_landing_zone_config_organization_managed_rule_map["config_${count.index}"]["name"]
          rule_identifier: >-
            local.elements_landing_zone_config_organization_managed_rule_map["config_${count.index}"]["rule_identifier"]
    output:
      arns:
        value: >-
          aws_config_organization_managed_rule.landing_zone_config_organization_managed_rule.*.arn
      landing_zone_config_organization_managed_rule_arns:
        value: >-
          { for config_organization_managed_rule in
          aws_config_organization_managed_rule.landing_zone_config_organization_managed_rule.*:
          config_organization_managed_rule.name =>
          config_organization_managed_rule.arn }
