component:
  name: landing_zone_route_pcx
  dependsOn:
    - landing_zone_route_table
    - landing_zone_vpc_peering_connection
  template:
    locals:
      elements_landing_zone_vpc_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"]
      elements_landing_zone_vpc_pcx_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_pcx_data"]
      elements_landing_zone_route_table_data_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_table_data"]
      elements_landing_zone_route_pcx_map: >-
        var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_pcx_resource"]
    data:
      aws_vpc:
        vpc_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_data"])
          cidr_block: >-
            local.elements_landing_zone_vpc_data_map["config_${count.index}"]["cidr_block"]
      aws_route_table:
        route_table_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_table_data"])
          vpc_id: 'element(data.aws_vpc.vpc_selected.*.id, count.index)'
          filter!:
            name: 'tag:LzHash'
            values:
              - >-
                local.elements_landing_zone_route_table_data_map["config_${count.index}"]["LzHash"]
      aws_vpc_peering_connection:
        vpc_peering_connection_selected:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_vpc_pcx_data"])
          filter!:
            - name: accepter-vpc-info.cidr-block
              values:
                - >-
                  local.elements_landing_zone_vpc_pcx_data_map["config_${count.index}"]["accepter_cidr_block"]
            - name: requester-vpc-info.cidr-block
              values:
                - >-
                  local.elements_landing_zone_vpc_pcx_data_map["config_${count.index}"]["requester_cidr_block"]
    resource:
      aws_route:
        landing_zone_route_pcx:
          provider: 'aws.${tfvar.terrahub["landing_zone_providers"]["0"]}'
          count: >-
            length(var.${tfvar.terrahub["landing_zone_providers"]["0"]}_provider["landing_zone_route_pcx_resource"])
          route_table_id: 'element(data.aws_route_table.route_table_selected.*.id, count.index)'
          destination_cidr_block: >-
            local.elements_landing_zone_route_pcx_map["config_${count.index}"]["destination_cidr_block"]
          vpc_peering_connection_id: >-
            element(data.aws_vpc_peering_connection.vpc_peering_connection_selected.*.id,
            count.index)
    output:
      ids:
        value: aws_route.landing_zone_route_pcx.*.id
      thub_ids:
        value: aws_route.landing_zone_route_pcx.*.id
      landing_zone_route_pcx_ids:
        value: >-
          { for route_pcx in aws_route.landing_zone_route_pcx.*: route_pcx.id =>
          route_pcx.id }
